version: 2
jobs:
  bundle_dependencies:
    working_directory: ~/syncpod
    docker:
      - image: circleci/ruby:2.4.2-node
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - attach_workspace:
          at: ~/syncpod
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: .
          paths: vendor/bundle

  rspec_test:
    working_directory: ~/syncpod
    docker:
      - image: circleci/ruby:2.4.2-node
        environment:
          RAILS_ENV: test
          GOOGLE_API_KEY: AIzaSyD7HERo0T7Lyhr_spJ9UTr4f3q7uUSNVSM
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - attach_workspace:
          at: ~/syncpod
      - run: cp config/database.yml.ci config/database.yml
      - run: bundle --path vendor/bundle
      - run: rails db:create
      - run: rails db:schema:load
      - run: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - bundle_dependencies
      - rspec_test:
          requires:
            - bundle_dependencies
